### ISSUE TITLE
Why not deprecate OpenDoorsInSpace(not the entire mod)

### ISSUE THREAD

**Issue by CatsArmy** [netux/LethalCompany-OpenDoorsInSpace#1]
im referring to [this specific one](https://thunderstore.io/c/lethal-company/p/netux/OpenDoorsInSpace/) as i see that the description says ❗ Old version. Use Open_Doors_in_Space instead.
so why not deperecate it instead of keeping both up?
![image](https://github.com/netux/LethalCompany-OpenDoorsInSpace/assets/104517593/8cff1f5d-25db-4079-a1b6-efc8d9e0ce70)

**Comment by netux** [comment]
I did deprecate it. Maybe Thunderstorm removed the deprecation flag since I pushed a version to update the description?

I deprecated it again. Let me know if it shows up as deprecated for you. May take a few minutes for Thunderstorm to update page.

**Comment by netux** [comment]
Old package has been deprecated, I will close this ticket
![image](https://github.com/netux/LethalCompany-OpenDoorsInSpace/assets/6181929/92b327b8-f60d-49dc-a6d6-b348c729caf6)
